import type { McpProvider, McpToolDefinition, McpToolResult } from './types';
import { writeSandboxFile, resolveSandboxPath } from '../sandbox';
import path from 'path';
import fs from 'fs/promises';

// ─── Tool Definitions ────────────────────────────────────────────
const tools: McpToolDefinition[] = [
  {
    name: 'write_markdown_doc',
    description:
      'Write a well-structured, presentable Markdown document to the sandbox. ' +
      'The content should use proper Markdown formatting: headings (#, ##, ###), ' +
      'lists, tables, bold/italic, blockquotes, code blocks, and horizontal rules. ' +
      'The output will be rendered with a Markdown previewer. ' +
      'Use this instead of sandbox_write_file when creating human-readable documents, reports, or presentations.',
    parameters: {
      type: 'object',
      properties: {
        path: {
          type: 'string',
          description: 'File path in the sandbox (should end in .md). E.g. "reports/renovation-plan.md"',
        },
        title: {
          type: 'string',
          description: 'Document title (rendered as H1 at the top)',
        },
        sections: {
          type: 'string',
          description:
            'JSON array of section objects. Each section has: ' +
            '"heading" (string, rendered as H2), ' +
            '"content" (string, Markdown-formatted body text — may include sub-headings ###, lists, tables, etc.), ' +
            '"subsections" (optional array of { "heading": string, "content": string } rendered as H3). ' +
            'Example: [{"heading":"Overview","content":"This project...","subsections":[{"heading":"Goals","content":"- Goal 1\\n- Goal 2"}]}]',
        },
        footer: {
          type: 'string',
          description: 'Optional footer text appended at the bottom (e.g. "Generated by AI Sandbox")',
        },
      },
      required: ['path', 'title', 'sections'],
    },
  },
  {
    name: 'create_pptx',
    description:
      'Create a PowerPoint (.pptx) presentation file in the sandbox. ' +
      'Provide a title, optional author, and an array of slides. Each slide has a title, ' +
      'body content (bullet points), and optional speaker notes. ' +
      'Great for creating professional presentations from structured data.',
    parameters: {
      type: 'object',
      properties: {
        path: {
          type: 'string',
          description: 'File path in the sandbox (should end in .pptx). E.g. "presentations/renovation.pptx"',
        },
        title: {
          type: 'string',
          description: 'Presentation title (used on the title slide)',
        },
        author: {
          type: 'string',
          description: 'Optional author/subtitle shown on the title slide',
        },
        slides: {
          type: 'string',
          description:
            'JSON array of slide objects. Each slide has: ' +
            '"title" (string), ' +
            '"bullets" (array of strings — each becomes a bullet point), ' +
            '"notes" (optional string — speaker notes for this slide), ' +
            '"layout" (optional: "title" for a section divider slide, or "content" for a normal slide — default is "content"). ' +
            'Example: [{"title":"Overview","bullets":["Point 1","Point 2"],"notes":"Discuss main goals"},{"title":"Budget","layout":"title"}]',
        },
      },
      required: ['path', 'title', 'slides'],
    },
  },
];

// ─── Argument Helpers ────────────────────────────────────────────

function extractPath(args: Record<string, unknown>): string {
  const raw = (args.path ?? args.file ?? args.filepath ?? args.filePath ??
    Object.values(args).find((v) => typeof v === 'string' && (v.endsWith('.md') || v.endsWith('.pptx')))) as string | undefined;
  if (!raw || typeof raw !== 'string') return '';
  let cleaned = raw.replace(/\\/g, '/');
  cleaned = cleaned.replace(/^.*?\/sandbox\//, '');
  cleaned = cleaned.replace(/^\/+/, '');
  return cleaned;
}

function parseJsonArg(val: unknown): any {
  if (typeof val === 'string') {
    try { return JSON.parse(val); } catch { return val; }
  }
  return val;
}

// ─── Markdown Document Builder ──────────────────────────────────

function buildMarkdown(args: Record<string, unknown>): string {
  const title = (args.title as string) || 'Untitled Document';
  const sections = parseJsonArg(args.sections) as any[];
  const footer = args.footer as string | undefined;

  const lines: string[] = [];

  // Title
  lines.push(`# ${title}`, '');

  // Table of Contents
  if (Array.isArray(sections) && sections.length > 1) {
    lines.push('## Table of Contents', '');
    sections.forEach((s, i) => {
      const heading = s.heading || `Section ${i + 1}`;
      const anchor = heading.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      lines.push(`${i + 1}. [${heading}](#${anchor})`);
    });
    lines.push('', '---', '');
  }

  // Sections
  if (Array.isArray(sections)) {
    for (const section of sections) {
      const heading = section.heading || 'Section';
      lines.push(`## ${heading}`, '');

      if (section.content) {
        lines.push(section.content, '');
      }

      // Subsections
      if (Array.isArray(section.subsections)) {
        for (const sub of section.subsections) {
          lines.push(`### ${sub.heading || 'Subsection'}`, '');
          if (sub.content) {
            lines.push(sub.content, '');
          }
        }
      }

      lines.push('---', '');
    }
  }

  // Footer
  if (footer) {
    lines.push('', `> ${footer}`);
  }

  lines.push('', `*Document generated on ${new Date().toLocaleDateString()}*`, '');

  return lines.join('\n');
}

// ─── PowerPoint Builder ─────────────────────────────────────────

async function buildPptx(args: Record<string, unknown>): Promise<Buffer> {
  // Dynamic import to avoid issues with SSR module resolution
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pres = new PptxGenJS();

  const title = (args.title as string) || 'Untitled Presentation';
  const author = (args.author as string) || '';
  const slides = parseJsonArg(args.slides) as any[];

  // Presentation metadata
  pres.author = author || 'AI Sandbox';
  pres.title = title;

  // Color scheme
  const COLORS = {
    primary: '2B579A',    // Dark blue
    secondary: '217346',  // Green
    accent: 'D24726',     // Orange-red
    bg: 'FFFFFF',
    text: '333333',
    lightBg: 'F0F4FF',
    subtle: '6C757D',
  };

  // ── Title Slide ──
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: COLORS.primary };
  titleSlide.addText(title, {
    x: 0.8, y: 1.5, w: 8.4, h: 1.8,
    fontSize: 32, fontFace: 'Segoe UI',
    color: 'FFFFFF', bold: true,
    align: 'left',
  });
  if (author) {
    titleSlide.addText(author, {
      x: 0.8, y: 3.4, w: 8.4, h: 0.6,
      fontSize: 16, fontFace: 'Segoe UI',
      color: 'B0C4E8', italic: true,
      align: 'left',
    });
  }
  titleSlide.addText(new Date().toLocaleDateString(), {
    x: 0.8, y: 4.2, w: 8.4, h: 0.4,
    fontSize: 12, fontFace: 'Segoe UI',
    color: 'B0C4E8',
    align: 'left',
  });

  // ── Content slides ──
  if (Array.isArray(slides)) {
    for (const s of slides) {
      const slide = pres.addSlide();
      const layout = s.layout || 'content';

      if (layout === 'title') {
        // Section divider slide
        slide.background = { color: COLORS.lightBg };
        slide.addText(s.title || '', {
          x: 0.8, y: 2.0, w: 8.4, h: 1.5,
          fontSize: 28, fontFace: 'Segoe UI',
          color: COLORS.primary, bold: true,
          align: 'left',
        });
        // Add a subtle underline
        slide.addShape(pres.ShapeType.rect, {
          x: 0.8, y: 3.5, w: 3, h: 0.06,
          fill: { color: COLORS.accent },
        });
      } else {
        // Standard content slide
        // Title bar area
        slide.addShape(pres.ShapeType.rect, {
          x: 0, y: 0, w: 10, h: 1.1,
          fill: { color: COLORS.primary },
        });
        slide.addText(s.title || '', {
          x: 0.5, y: 0.15, w: 9, h: 0.8,
          fontSize: 22, fontFace: 'Segoe UI',
          color: 'FFFFFF', bold: true,
          align: 'left',
        });

        // Bullet content
        const bullets = Array.isArray(s.bullets) ? s.bullets : [];
        if (bullets.length > 0) {
          const bodyRows = bullets.map((b: string) => ({
            text: b,
            options: {
              fontSize: 14,
              fontFace: 'Segoe UI',
              color: COLORS.text,
              bullet: { type: 'bullet' as const },
              paraSpaceAfter: 6,
            },
          }));
          slide.addText(bodyRows, {
            x: 0.8, y: 1.4, w: 8.4, h: 4.0,
            valign: 'top',
          });
        }
      }

      // Speaker notes
      if (s.notes) {
        slide.addNotes(s.notes);
      }
    }
  }

  // Generate buffer
  const output = await pres.write({ outputType: 'nodebuffer' });
  return output as Buffer;
}

// ─── Provider Implementation ─────────────────────────────────────

async function execute(
  toolName: string,
  args: Record<string, unknown>,
): Promise<McpToolResult> {
  try {
    switch (toolName) {
      case 'write_markdown_doc': {
        const p = extractPath(args);
        if (!p) return { success: false, data: null, error: 'path is required (e.g. "reports/my-doc.md")' };
        const finalPath = p.endsWith('.md') ? p : `${p}.md`;
        const content = buildMarkdown(args);
        await writeSandboxFile(finalPath, content);
        return {
          success: true,
          data: `Markdown document written: ${finalPath} (${content.length} chars, ready for preview)`,
        };
      }

      case 'create_pptx': {
        const p = extractPath(args);
        if (!p) return { success: false, data: null, error: 'path is required (e.g. "presentations/deck.pptx")' };
        const finalPath = p.endsWith('.pptx') ? p : `${p}.pptx`;
        const buffer = await buildPptx(args);

        // Write binary file directly to sandbox
        const absPath = resolveSandboxPath(finalPath);
        await fs.mkdir(path.dirname(absPath), { recursive: true });
        await fs.writeFile(absPath, buffer);

        const slides = parseJsonArg(args.slides);
        const slideCount = Array.isArray(slides) ? slides.length + 1 : 1; // +1 for title slide
        return {
          success: true,
          data: `PowerPoint created: ${finalPath} (${slideCount} slides, ${(buffer.length / 1024).toFixed(1)} KB)`,
        };
      }

      default:
        return { success: false, data: null, error: `Unknown tool: ${toolName}` };
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, data: null, error: message };
  }
}

export const documentProvider: McpProvider = {
  name: 'document',
  description: 'Document generation tools: create well-formatted Markdown files and PowerPoint presentations in the sandbox.',
  tools,
  execute,
};
